Revert "fbdev: Ditch fb_edid_add_monspecs" - exynos dpu is still relying on this ../drivers/video/fbdev/exynos/dpu/displayport_edid.c: In function ‘edid_update’: ../drivers/video/fbdev/exynos/dpu/displayport_edid.c:513:3: error: implicit declaration of function ‘fb_edid_add_monspecs’; did you mean ‘fb_edid_to_monspecs’? [-Werror=implicit-function-declaration]    fb_edid_add_monspecs(edid + i * EDID_BLOCK_SIZE, &specs);    ^~~~~~~~~~~~~~~~~~~~    fb_edid_to_monspecs cc1: some warnings being treated as errors ../scripts/Makefile.build:277: recipe for target 'drivers/video/fbdev/exynos/dpu/displayport_edid.o' failed make[6]: *** [drivers/video/fbdev/exynos/dpu/displayport_edid.o] Error 1 make[6]: *** Waiting for unfinished jobs....
This reverts commit 2de822c88287e956f5f127d37cbf1d44d0193237.